language: node_js
node_js:
  - "8.6.0"
env:
  - NODE_ENV=travis CXX=g++-4.8

services:
  - postgresql
before_script:
  - psql -c 'create database aspen;' -U postgres

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

